# Generated by Django 4.1.4 on 2023-09-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pontoturistico_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='enderecos',
            new_name='endereco',
        ),
    ]
